/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal.project;

import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Jettman737
 */
public class MainPanel extends javax.swing.JFrame {
    BookStoreSystem system = BookStoreSystem.getInstance();



    public MainPanel() {
        initComponents();
        setLocationRelativeTo(null);
        
        OwnerStartPanel start = new OwnerStartPanel();
        OwnerBooksPanel books = new OwnerBooksPanel();
        OwnerCustomerPanel customers = new OwnerCustomerPanel();

        OwnerDashboardPanel.removeAll();
        OwnerDashboardPanel.setLayout(new CardLayout());

        OwnerDashboardPanel.add(start, "ownerStart");
        OwnerDashboardPanel.add(books, "books");
        OwnerDashboardPanel.add(customers, "customers");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        Login = new javax.swing.JPanel();
        UsernameLabel = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        LoginButton = new javax.swing.JButton();
        PasswordLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CustomerDashboardPanel = new javax.swing.JPanel();
        customerDashboard1 = new pkgfinal.project.CustomerDashboard();
        OwnerDashboardPanel = new javax.swing.JPanel();
        ownerStartPanel2 = new pkgfinal.project.OwnerStartPanel();
        ownerCustomerPanel2 = new pkgfinal.project.OwnerCustomerPanel();
        ownerBooksPanel2 = new pkgfinal.project.OwnerBooksPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 900));
        getContentPane().setLayout(new java.awt.CardLayout());

        Main.setPreferredSize(new java.awt.Dimension(1200, 900));
        Main.setLayout(new java.awt.CardLayout());

        Login.setPreferredSize(new java.awt.Dimension(1200, 900));

        UsernameLabel.setText("Username:");

        UsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFieldActionPerformed(evt);
            }
        });

        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        PasswordLabel.setText("Password:");

        jLabel1.setText("Welcome to the BookStore App");

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                        .addContainerGap(558, Short.MAX_VALUE)
                        .addComponent(LoginButton)
                        .addGap(80, 80, 80))
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addContainerGap(490, Short.MAX_VALUE)
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PasswordLabel)
                            .addComponent(UsernameLabel))
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addContainerGap(490, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addContainerGap(366, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameLabel)
                    .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(LoginButton)
                .addContainerGap(367, Short.MAX_VALUE))
        );

        Main.add(Login, "card2");

        CustomerDashboardPanel.setPreferredSize(new java.awt.Dimension(1200, 900));
        CustomerDashboardPanel.setLayout(new java.awt.BorderLayout());
        CustomerDashboardPanel.add(customerDashboard1, java.awt.BorderLayout.CENTER);

        Main.add(CustomerDashboardPanel, "card3");

        OwnerDashboardPanel.setLayout(new java.awt.CardLayout());
        OwnerDashboardPanel.add(ownerStartPanel2, "card2");
        OwnerDashboardPanel.add(ownerCustomerPanel2, "card3");
        OwnerDashboardPanel.add(ownerBooksPanel2, "card4");

        Main.add(OwnerDashboardPanel, "card4");

        getContentPane().add(Main, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        String username = UsernameField.getText();
        String password = PasswordField.getText();

        boolean success = system.login(username, password);

        if (success) {
            User user = system.getCurrentUser();
            UsernameField.setText("");
            PasswordField.setText("");

            if (user instanceof Owner) {
                switchToOwnerStartScreen();
            } else if (user instanceof Customer) {
                switchToCustomerStartScreen((Customer) user);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Invalid username or password");
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CustomerDashboardPanel;
    private javax.swing.JPanel Login;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel OwnerDashboardPanel;
    private javax.swing.JTextField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel UsernameLabel;
    private pkgfinal.project.CustomerDashboard customerDashboard1;
    private javax.swing.JLabel jLabel1;
    private pkgfinal.project.OwnerBooksPanel ownerBooksPanel2;
    private pkgfinal.project.OwnerCustomerPanel ownerCustomerPanel2;
    private pkgfinal.project.OwnerStartPanel ownerStartPanel2;
    // End of variables declaration//GEN-END:variables



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPanel().setVisible(true);
                
            }
        });
    }
    
    private void switchToOwnerStartScreen() {
        ((CardLayout) OwnerDashboardPanel.getLayout()).show(OwnerDashboardPanel, "ownerStart");
        ((CardLayout) Main.getLayout()).show(Main, "card4");
    }

    private void switchToCustomerStartScreen(Customer c) {
        ((CardLayout) Main.getLayout()).show(Main, "card3");
    }



}
